-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : mer. 03 nov. 2021 à 00:58
-- Version du serveur :  5.7.31
-- Version de PHP : 7.3.21

SET SQL_MODE
= "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone
= "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `blog_openclassroom`
--

-- --------------------------------------------------------

--
-- Structure de la table `comment`
--

DROP TABLE IF EXISTS `comment`;
CREATE TABLE
IF NOT EXISTS `comment`
(
  `id` int
(11) NOT NULL AUTO_INCREMENT,
  `author` varchar
(255) NOT NULL,
  `content` text NOT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `validated` tinyint
(1) NOT NULL DEFAULT '0',
  `postId` int
(11) UNSIGNED NOT NULL,
  PRIMARY KEY
(`id`),
  KEY `post_id`
(`postId`)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `comment`
--

INSERT INTO `comment` (`
id`,
`author
`, `content`, `createdAt`, `validated`, `postId`) VALUES
(3, 'Moi', 'Merci !', '2021-09-21 17:04:52', 1, 31),
(4, 'Moi', 'Merci pour cet article', '2021-09-08 17:04:52', 0, 30),
(17, 'boum', 'tres bien', '2021-10-23 12:33:05', 1, 31),
(38, 'boum', 'tres bel article!\r\n', '2021-10-30 17:54:39', 1, 32),
(43, 'boum', 'bonjour', '2021-11-03 00:56:50', 1, 41);

-- --------------------------------------------------------

--
-- Structure de la table `post`
--

DROP TABLE IF EXISTS `post`;
CREATE TABLE
IF NOT EXISTS `post`
(
  `id` int
(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` varchar
(255) NOT NULL,
  `author` varchar
(255) NOT NULL,
  `chapo` varchar
(255) NOT NULL,
  `content` text NOT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY
(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `post`
--

INSERT INTO `post` (`
id`,
`title
`, `author`, `chapo`, `content`, `createdAt`) VALUES
(1, 'Article #1', 'auteur-1', 'faciliset-estvitaeteneturiste-delectus', 'Veritatis et sunt laboriosam aut. Enim voluptas quos molestiae veritatis. Quae illum possimus laudantium omnis et atque voluptas et. Nihil dolor sunt autem sint quia.\r\n\r\nDelectus officiis quo rerum magni. Doloribus autem reprehenderit iusto aliquam non voluptatem accusantium. Sint aspernatur aut aliquid qui.\r\n\r\nVitae ratione optio aliquam voluptas illum voluptas. Est quis facilis praesentium placeat ducimus dolorum distinctio earum.', '2005-04-30 18:09:15'),
(5, 'Article #5', 'auteur-5', 'ut-sed-esse-sint-iusto-rerumt-sed-es', 'Id minus accusamus aspernatur sapiente. Nam est beatae quia labore. Voluptatem sequi voluptatum laudantium culpa repellendus aperiam id ad. Rerum qui animi sunt eos minima blanditiis nulla.\n\nMollitia est ea aut quaerat. Enim doloribus illo quo omnis natus. Odio nihil quos illo voluptas laboriosam.\n\nUt voluptatem quidem molestiae totam quis ipsum non. Id praesentium placeat quia nostrum magnam. Est ratione dolorum eos architecto minima omnis.\n\nQui sunt dolores quia iure. Asperiores earum assumenda omnis ex dolores dolores ut fugit.\n\nAutem voluptas aspernatur ducimus maxime doloribus voluptatibus. Quae vitae accusantium voluptas voluptatem. Sapiente iste neque laborum consequatur incidunt dicta molestias error.\n\nLibero enim distinctio accusantium consequuntur odit quae iusto. Qui autem placeat qui ut qui non.\n\nSaepe laboriosam tempore aperiam est illo qui aperiam. Quia error laborum a aspernatur eum et. Commodi id quibusdam enim in.\n\nRerum quisquam omnis et et modi sed ut. Similique pariatur qui beatae ut. Pariatur esse in dolor totam delectus.\n\nCorporis odio enim et. Temporibus exercitationem ipsam aut quaerat quam. Inventore illum a voluptatem sunt nostrum. Et est voluptatum quos.', '1991-06-24 08:43:42'),
(9, 'Article #9', 'auteur-9', 'dolorem-sunt-voluptate-quidem--sunt-', 'Assumenda excepturi itaque voluptas. Repellendus reiciendis dolorum deserunt doloribus sed commodi. Vero debitis qui ut atque et eos nihil. Enim et sequi laboriosam sunt fugiat aut.\r\n\r\nVoluptas similique modi aut maxime ad autem itaque. Debitis omnis earum consequatur. Dignissimos a qui voluptatem et omnis magni omnis consequatur.\r\n\r\nNulla placeat qui suscipit vel atque id. Ratione ea accusamus distinctio temporibus. Odit a rerum cumque vero.', '1993-08-17 01:32:56'),
(10, 'Article #10', 'auteur-10', 'numquam-maiores-qui-numquam-consequatur', 'Sint corporis necessitatibus nobis dolores aliquam voluptatem neque. Voluptatem ducimus hic accusantium eos. Illo consequatur consequatur qui sunt nihil eius qui. Ut rerum aut et et sunt dolorem omnis. Consequuntur quibusdam sit adipisci sunt rerum voluptatibus vero eius.\r\n\r\nNihil laudantium earum laudantium. Eveniet blanditiis voluptatem hic eaque voluptatem. Itaque ut beatae aliquam sint nesciunt animi veritatis.\r\n\r\nOccaecati qui alias enim. Enim nisi dolorem numquam ut dolorum dolore quis.\r\n\r\nMolestiae aliquam ab eum eius non est optio blanditiis. Doloremque consectetur autem dignissimos doloremque deserunt nulla non quae. Incidunt soluta qui ab ullam qui consequatur.\r\n\r\nFuga aspernatur culpa porro rerum. Et praesentium veniam nulla quod doloribus nisi aperiam.\r\n\r\nLabore aperiam maxime necessitatibus earum illo quia ipsum. Molestiae adipisci rem vel iste fugiat. Ut qui similique nisi non illo.\r\n\r\nMinima consectetur qui nisi fuga impedit. Consequuntur qui nisi enim deleniti provident. Aliquid odio tempora quo molestias non sunt id. Et dolores quia sed sunt eveniet illum.\r\n\r\nReiciendis odit quas reiciendis velit aut distinctio sit error. Dolores et itaque dolores iste voluptatem placeat. Odio ipsam hic ea numquam est natus sint. Aut eius veniam similique non quidem reprehenderit. Et aliquid temporibus sunt aperiam molestiae at et.\r\n\r\nIncidunt nostrum vel natus accusantium rerum sint non. Esse consectetur hic expedita aliquam quia reprehenderit. Consequatur non quidem quia rerum est qui.\r\n\r\nEveniet odit sit est corporis. Similique optio ea quis nesciunt temporibus quos. Nobis magni qui adipisci omnis quae reprehenderit.\r\n\r\nNon est aut repellat. Cupiditate qui voluptatem sed quis labore saepe eum. Suscipit eum dolor molestiae corrupti rem.\r\n\r\nIncidunt temporibus sit aperiam possimus et voluptatem quo. Ut tenetur et reiciendis laborum est dignissimos voluptas totam. Sunt dolorem veniam temporibus et officiis error suscipit.\r\n\r\nIpsam nulla repellat odit id quidem sunt. Illo in nihil unde eum. Inventore quia perspiciatis mollitia incidunt quaerat illo dolores.\r\n\r\nFugiat officia qui modi vitae ut voluptatem esse ducimus. Ea veritatis similique eos ut quia.\r\n\r\nEos id id et voluptatem consequatur. Quia ea consequatur non ut. Magni neque est dignissimos consectetur ea praesentium.', '1982-05-01 19:00:24'),
(19, 'Article #19', 'auteur-19', 'et-placeat-voluptatum-ratione-aliquid', 'Nihil in doloribus sunt tenetur quia reiciendis harum id. Molestiae esse deserunt exercitationem officiis velit est. Atque nihil consequatur ut distinctio.\r\n\r\nDicta cupiditate asperiores dolore minus voluptas. Accusantium dolorum provident omnis voluptas aut. Repellat placeat commodi velit ratione. Fuga cumque quia sed deleniti aut. Quis vero et sunt labore.\r\n\r\nDeleniti nam iure illo voluptatem esse cupiditate pariatur aut. Eos sapiente alias maiores dolores minus distinctio. Quo corporis est sint et.\r\n\r\nProvident cumque molestias in animi dolorem qui. Soluta id voluptatum voluptatem delectus velit quae explicabo. Eos labore suscipit voluptatem magnam iusto maxime.\r\n\r\nQuam maxime qui delectus et. Repudiandae quos molestias id et ut natus expedita ut. Et deserunt dicta tempore perferendis qui. Praesentium sit inventore laboriosam non.\r\n\r\nExplicabo eum mollitia fugiat nulla illum eligendi excepturi deleniti. Et soluta veniam quod perspiciatis autem et exercitationem ea. Occaecati accusantium nesciunt voluptatum a. Dolore exercitationem dolorem dolores et animi voluptatem.\r\n\r\nError suscipit ex itaque voluptatem. Voluptas maiores nobis vel deleniti eligendi. Nam corporis deleniti molestiae quos omnis consequatur in autem. Et sint ducimus pariatur voluptatem necessitatibus quo eligendi.', '1983-07-15 08:44:47'),
(20, 'Article #20', 'auteur-20', 'excepturi-voluptas-maiores-repudiandae-', 'Dolorem omnis aperiam commodi quia. Tempore repudiandae quaerat voluptatum excepturi dolor deleniti aut totam.\r\n\r\nDolores molestiae quaerat illo consequatur dolore architecto. Quod qui nobis eum aspernatur dolor magnam. Quibusdam a corrupti voluptatum dolorem ex tempore. Consequatur maxime distinctio amet eligendi in earum dolores. Ut consectetur vel quo dignissimos.\r\n\r\nNihil dignissimos velit architecto eum et cum. Nisi inventore quaerat aliquam minima omnis. Et libero qui ullam optio sit.\r\n\r\nEum enim id nobis quo ex eaque. Libero eveniet aliquid consequatur animi in et. Quas non debitis consequuntur quo.\r\n\r\nAut facilis repudiandae est quisquam et aut ut officia. Nihil a sunt est aut. Veniam voluptatum omnis vero labore eaque porro.\r\n\r\nQuia magni officiis corporis et cupiditate enim quas beatae. Mollitia impedit ullam culpa qui dolorum. Fugiat commodi sit eius soluta ratione laudantium recusandae.\r\n\r\nConsequatur doloremque libero exercitationem quidem. Repellendus voluptatem qui dicta. Quam veniam aliquam dolores. Dolor est dignissimos enim est molestiae vel voluptatum perspiciatis.\r\n\r\nFuga eos autem et quae odio et. A blanditiis ea rerum. Rem tempore aspernatur tempore molestias. Voluptate eos illum quaerat cumque rem voluptate deleniti id.\r\n\r\nMinus nihil voluptas animi dolor quisquam quos ratione. Recusandae ut fuga molestias atque mollitia architecto in. Quia non consequuntur omnis. Ea quo qui esse ab. Quaerat omnis sit nihil.', '1992-07-08 05:44:15'),
(21, 'Article #21', 'auteur-21', 'fugiat-commodi-autem-labore-tempore-', 'Praesentium consectetur ratione ratione reprehenderit autem. Nisi sunt quis culpa nisi excepturi quo. Ea sint dolor dolor dolore quia tenetur.\r\n\r\nAutem aspernatur saepe error similique amet sed beatae. Accusamus eum ullam tenetur recusandae molestiae vitae quia. Sit deleniti iste modi voluptate officiis. Qui omnis animi optio velit at aliquid itaque.\r\n\r\nOfficiis corporis iste officia voluptatibus. Dolorem qui laborum adipisci ea. Omnis quod molestiae magnam tempora optio repellat natus adipisci. Ipsam dolor quaerat beatae quam et commodi quia.\r\n\r\nReprehenderit eos quae sint in veritatis tempore. Et voluptas ratione dolor expedita velit quis. Minus asperiores omnis qui totam temporibus veniam. Sit modi enim maiores est sunt.\r\n\r\nAutem explicabo sint odit. Nihil dolore rem dolores corporis placeat. Ut ab fugiat excepturi rerum ipsam beatae et et. Voluptatibus explicabo fugit nulla eveniet neque doloremque amet.\r\n\r\nOfficiis et voluptatem eum et quis minus. Et molestiae eligendi quas repellendus consequatur qui. Tempore provident autem molestiae labore quia repellat aperiam est.\r\n\r\nIncidunt fugiat earum corrupti minus nemo et. Quis libero maxime doloribus. Aperiam maiores facere aut qui.', '1991-02-14 16:58:59'),
(22, 'Article #22', 'auteur-22', 'odiosed-id-ea-qui-quos-ab-commo-sed-id-ea-', 'Illum nobis nulla voluptatem doloremque ipsam ducimus. Quia soluta aliquid ad ad velit aut. Praesentium in vero quos eos.<br />\r\n<br />\r\nEarum officiis commodi libero vero aut laborum. Qui accusantium autem vitae molestias ut sunt enim.<br />\r\n<br />\r\nPorro et architecto rerum et consequuntur culpa laborum. Nostrum velit culpa rem commodi. Repellat cupiditate quia aliquid voluptatem.<br />\r\n<br />\r\nVoluptates sed fugiat optio explicabo vel tenetur. Libero et voluptates eveniet aliquid. Veritatis qui minus nemo natus ducimus. Fugiat rerum laudantium earum recusandae.<br />\r\n<br />\r\nIusto ipsa sed dolore. Nostrum quibusdam nesciunt minima sed. Maiores dolores laudantium expedita laborum voluptatem et.<br />\r\n<br />\r\nLabore facilis quis dolores sint neque soluta. Nesciunt nulla iusto omnis. Nesciunt delectus praesentium molestiae commodi.<br />\r\n<br />\r\nQuia inventore illo qui ea. Vero quasi quas deleniti voluptatem. Qui ut nihil eos ex mollitia. Suscipit esse exercitationem debitis quo. Ad a quisquam dolore sunt.<br />\r\n<br />\r\nEt placeat non nihil recusandae. Suscipit placeat maiores inventore. Recusandae vel ad aut cupiditate modi non. Non ut est doloremque sed aperiam provident impedit aut.<br />\r\n<br />\r\nAut velit iusto ut assumenda. Autem aut sunt nisi est voluptas at eius libero. Optio quam non nihil dolorum eum. Minima minus et quia debitis sed.<br />\r\n<br />\r\nDignissimos qui cupiditate labore repudiandae quia et. At dolor aut odit id sunt officia ipsum. Quibusdam ducimus quam provident est.<br />\r\n<br />\r\nSunt saepe sint qui culpa neque. Ut sint vel optio aut tempora exercitationem ipsam. Modi minus quas qui in. Sint rerum esse est. Maxime enim dolor maiores recusandae aut.<br />\r\n<br />\r\nOdio autem repellat maxime vero amet pariatur illum. Placeat natus quisquam minima. Consequatur a soluta et aut repellendus rerum. Et error ut nihil velit adipisci sit.', '1998-11-25 12:12:06'),
(24, 'Article #24', 'auteur-24', 'debitis-sed-id-ea-est-rerumsed-id-ea-', 'Aut alias cumque doloribus eaque assumenda. Blanditiis impedit neque labore doloremque cumque. Quia et rerum quaerat blanditiis. Cupiditate sed repellendus qui adipisci et quae. Asperiores omnis labore occaecati eligendi ea eligendi.\n\nDeserunt architecto aut accusamus voluptas consequuntur. Omnis eius voluptas nostrum sed dolorem. At aut veritatis est totam fugit aspernatur id.\n\nQui pariatur qui velit vel quia omnis adipisci. Doloribus blanditiis inventore earum sit sapiente quia accusantium. Quia maxime error sunt iste. Qui qui maiores minima non sunt veniam modi. Minima quaerat delectus atque reiciendis rerum sequi.\n\nArchitecto et ea natus asperiores velit tempora facilis. Assumenda error omnis omnis. Ex ratione sed et eos aut.\n\nAt nesciunt suscipit illo reprehenderit suscipit qui mollitia. Quo est sed totam similique. Ullam quasi necessitatibus qui reiciendis et. Ratione dolore quibusdam sapiente quis qui iusto natus possimus. Ratione nihil totam mollitia ut quasi.\n\nLaborum autem id fugit nisi sit amet. Rerum sapiente sit voluptate atque. Et recusandae et voluptas nesciunt soluta explicabo rerum. Ut voluptatum nostrum tempore doloribus.\n\nQuo adipisci sunt fuga praesentium nulla pariatur. Vel sit quasi id porro. Et nihil suscipit est iste animi vitae consequatur quo.\n\nFugiat nemo omnis maiores aperiam eum nesciunt. Et quas quidem officiis est quasi qui. Hic ut qui exercitationem repudiandae quasi.', '1997-03-07 12:03:24'),
(26, 'Article #26', 'auteur-26', 'maxime-commodi-perferendis-aut-me-commod', 'Alias animi odio corrupti quo rerum. Laudantium consequatur culpa quo qui. Ut dolorem at quia sed labore voluptates recusandae quia.\r\n\r\nDebitis veniam corrupti repellendus dicta nostrum doloremque et. Culpa aspernatur placeat beatae reiciendis. Est consequatur aut voluptatem vel.\r\n\r\nAnimi ipsam earum ullam accusantium eum voluptas. Tempore et ut tenetur molestiae itaque possimus. Laboriosam molestiae optio consequuntur dolorem tempora.\r\n\r\nImpedit eos assumenda labore. Voluptates quo alias veritatis laboriosam et nostrum aut. Autem rerum sapiente quis distinctio facere. Totam assumenda sed eos sed ut id ipsum.\r\n\r\nRerum laudantium qui praesentium autem deleniti aut veniam. Earum vero tenetur sit nobis est.\r\n\r\nOdio ea labore non. Nobis et reprehenderit ex ut velit cumque. Ea qui quaerat maiores ducimus excepturi.\r\n\r\nTempora optio qui accusamus quaerat. Velit atque deleniti cumque. Inventore vero omnis nisi quidem mollitia qui id. Asperiores quis necessitatibus modi.', '2000-12-28 10:54:02'),
(28, 'Article #28', 'auteur-28', 'ratione-commodi-dolores-et-fugaatione', 'Quibusdam amet animi nihil minima. Tempore ex voluptatem molestiae ut molestias et. Sit laborum autem voluptatem consequatur sit quis qui.\r\n\r\nDoloribus ullam corrupti sapiente animi debitis eius non sint. Deserunt doloremque aliquid nemo aliquid. Facere nulla animi modi ab nihil. Sed ea ullam nemo similique quia.\r\n\r\nQui tenetur vero tempore quae ipsa ipsa voluptatem. Perferendis et quia quis aliquam accusamus.\r\n\r\nConsequatur sit quos dolor illo eos. Enim cum omnis non inventore rerum.\r\n\r\nQuia quo sit quia qui inventore. Officia qui ut voluptates quos magni dolor voluptas. Enim veritatis incidunt facilis ut voluptatem. Molestias amet expedita recusandae et.\r\n\r\nNobis facere officia molestiae est nulla id. Excepturi voluptas voluptatem aut sint occaecati dolores excepturi.\r\n\r\nQuaerat dolorem quam similique dolorem culpa et totam. Qui est sint qui sit sapiente excepturi. Aliquam quaerat ducimus sit et voluptas non similique sit. Illo aut repellendus maiores aut aut fuga.\r\n\r\nIn ducimus omnis harum incidunt accusamus porro nam. Quisquam explicabo exercitationem vel quo doloribus. Alias enim dolorum id enim magnam reiciendis. Sunt rerum rem quis omnis dolores.\r\n\r\nEt porro alias saepe sit quasi qui. Perspiciatis eos ea quia excepturi dolor totam. Consequatur quaerat voluptatem vel. Ut temporibus est animi et rerum.', '1978-09-04 18:05:51'),
(30, 'Article #30', 'auteur-30', 'quaerat-nobis-incidunt-aliquamatione', 'Consequuntur laudantium deserunt adipisci. Ullam quo ut voluptas quia voluptatem. Voluptatem autem laboriosam necessitatibus consectetur ea. Molestiae et dolor voluptates suscipit.\r\n\r\nEligendi voluptatem enim delectus et doloribus. Voluptas et tempora quia assumenda nemo aperiam assumenda. Aspernatur et commodi beatae corporis. Reprehenderit nobis sed incidunt repellendus commodi deleniti doloribus voluptatem.\r\n\r\nQuae reiciendis soluta veniam accusamus. At ea ipsam omnis similique quia culpa. Ab culpa voluptatem beatae deleniti culpa consequuntur.\r\n\r\nTempora pariatur ipsa harum officiis. Voluptate modi ullam eos quia deserunt est.', '1992-05-08 21:30:12'),
(31, 'Article #31', 'auteur-31', 'maiores-a-doloribus-similique-quam', 'Odit \r\noptio temporibus dolorem exercitationem necessitatibus rem non. Deserunt ipsa necessitatibus ipsa occaecati. Fugiat quisquam recusandae dolore quis. Quia rejjhjhpellat et ut pjhjhjrovident.\r\njjhhj\r\nSit nulla eius quibusdam qui id. Voluptate id ea qui sed laudantium eum nostrum. Nihil asperiores eum ratione et assumenda veniam laboriosam.\r\n\r\nQuia consequatur voluptate asperiores voluptatum autem iste. Ut consequatur explicabo adipisci est. Quas et voluptatem quos. Dolor ut in non consequatur perspiciatis qui magni nesciunt.\r\n\r\nLabore rerum minus et quaerat qui. Illum doloremque vel mollitia est corporis quam quos. Aut quisquam labore ab similique ratione est.\r\n\r\nQui enim qui et accusantium non porro. Molestias accusantium debitis amet consectetur possimus molestiae debitis. Quaerat enim facere ad dolorem reprehenderit exercitationem ut omnis. Tempore fuga temporibus blanditiis consequatur.', '2010-01-07 23:27:36'),
(32, 'Article #32', 'auteur-32', 'et-quisquam-ipsam-pariatur-rerum-', 'Ab nostrum quibusdam sed culpa ratione reprehenderit. Quam aut rerum non est et. Dolorem facere deserunt velit ex voluptas tempora.\r\n\r\nAut saepe ut facilis. Alias sed quibusdam quasi sit. Placeat odio dignissimos recusandae fuga quis. Nisi expedita nisi beatae vel recusandae saepe similique.\r\n\r\nAut sed explicabo impedit ipsa facere sed error. Est in voluptatibus ducimus. Atque inventore ut sed molestiae voluptatem. Veritatis nam nemo quia omnis in molestiae rem sapiente.\r\n\r\nRatione nulla optio culpa ipsum. Voluptatum nisi id nihil rerum non. Perferendis et rerum nulla. Et sit dignissimos ut ut.\r\n\r\nDebitis repellat illum quis repudiandae eligendi et. Aspernatur ut minima ad voluptate quasi quaerat. Et excepturi neque et sunt deserunt. Dolore qui omnis ut.\r\n\r\nSint consequatur et nam officiis voluptas voluptas. Ipsum qui illo nemo eos numquam. Aut veritatis soluta optio dolore temporibus dolorum consequatur.\r\n\r\nQuibusdam temporibus sed velit itaque. Amet exercitationem consequatur eius.\r\n\r\nSed tenetur enim et. Laboriosam in deserunt et fugit deserunt praesentium veniam. Neque aut eaque aut eum doloremque eius. Cupiditate aut mollitia voluptas aperiam.\r\n\r\nQuo alias et vero quibusdam placeat dolore blanditiis. Tenetur beatae consequatur aperiam autem nisi. Et dolorum voluptatibus pariatur et ea.\r\n\r\nExplicabo saepe ipsum ipsum velit voluptatem impedit distinctio. Sint fugit ut aperiam ut et voluptatem. Nihil aut molestiae nam rerum iste. Quis sunt voluptatibus tempore eos. Rerum non dolor quidem facilis accusamus adipisci.\r\n\r\nEst maiores sed illum numquam. Cum tempore eaque aut. Perferendis nihil atque eum provident nulla.', '1995-10-23 05:02:50'),
(37, 'Article #37', 'auteur-37', 'a-ea-et-sed-aliquam-corporis-assumenda', 'Incidunt et aliquam id tempora expedita omnis voluptatibus. Sit quas pariatur a eveniet voluptatem laborum. Quaerat vero similique consequatur.\r\n\r\nAlias blanditiis voluptatem dolor at. Dolorum ratione doloribus animi natus omnis voluptatem voluptatem. Aspernatur saepe cumque cumque natus.\r\n\r\nModi earum sapiente possimus aperiam voluptate voluptas nobis. Tempora assumenda est quisquam aliquam. Est est quia voluptatem dolores. Est corporis et aspernatur quia earum est.\r\n\r\nMinus assumenda quam consequatur saepe qui ut. Saepe et earum harum deleniti. Et aliquam accusamus est. Soluta eius iusto sequi qui.\r\n\r\nAmet dolores veritatis voluptas reprehenderit sequi consequatur ipsam. Tempore consequatur ad facere ipsam. Qui modi qui dolore veritatis odio sapiente et quia. Ipsam laudantium perferendis vel numquam omnis velit.\r\n\r\nEveniet dignissimos aliquid totam quia qui. Hic aliquid quis maxime corrupti labore laboriosam et. Molestias earum fugit iste aspernatur culpa expedita aspernatur.\r\n\r\nFuga ipsam alias tenetur voluptatem. In fugiat nam ipsum voluptate similique ducimus cumque accusantium.\r\n\r\nOccaecati assumenda quia sapiente rerum voluptas. Sit officiis asperiores sapiente. Repellat reiciendis amet nulla deserunt in.\r\n\r\nSit numquam quo ut laudantium praesentium ipsam vel. Repellat magni et ab minima nemo quia. Voluptatibus ipsum porro consequatur molestiae. In illum est non perferendis aut.\r\n\r\nIpsam vel aut omnis rerum culpa explicabo quia aperiam. Et sequi unde fugiat voluptas.', '1980-08-02 18:05:41'),
(38, 'Article #38', 'auteur-38', 'cum-autem-voluptatibus-libero-um-autem', 'Tenetur delectus sint consequatur totam sit suscipit. Corporis est et omnis. Deleniti atque quae amet repellat libero. Rerum ullam rerum tempora perspiciatis. Deleniti praesentium explicabo voluptas a officiis fuga saepe laudantium.\r\n\r\nDelectus explicabo quae eum accusamus accusamus perspiciatis eligendi. Velit impedit explicabo voluptatem aut iste error velit molestias. Voluptates aut facilis et aut earum. Corrupti consequatur alias nemo.\r\n\r\nNostrum dicta reprehenderit ut quos. Fugiat eaque impedit consequatur ut. Rerum est possimus repudiandae totam ut nesciunt.\r\n\r\nQuas molestiae beatae et ipsum et ab autem. Deleniti atque autem voluptatibus ducimus dolores reprehenderit. Tenetur alias et sit ut. Est odit mollitia veniam id nobis voluptatem.\r\n\r\nVeritatis quas tempore totam quo voluptatem soluta est nisi. Aspernatur ratione corporis aut necessitatibus a aliquam. Vitae dolorum debitis odio facere voluptatem. Impedit fugiat et sequi. Inventore rem cumque ut amet ex blanditiis.\r\n\r\nNumquam rerum quia odio enim. Ut quidem laboriosam consectetur ipsa. Repellat magni illum aut quis. Quo ut sed placeat doloremque.\r\n\r\nSimilique corrupti repudiandae nulla assumenda qui fugit. Sit voluptatibus dolore vel maxime culpa porro id. Sint autem et dicta accusamus eum. Molestias ipsa sit in hic quas facilis eum.\r\n\r\nDelectus et magni non id id autem. Dolores veritatis eos in error. Sed asperiores ea sint et vel modi est. Et nisi quia dolores architecto laborum voluptatum veniam.\r\n\r\nAut nemo culpa aut neque quia dignissimos. Et quis dolore vero quam. Incidunt ut sit nulla eos. Doloremque voluptatem architecto consequatur itaque.', '2007-03-16 03:11:40'),
(39, 'Article #39', 'auteur-39', 'nulla-est-hic-vel-qui-soluta-quasi-voluptas', 'Beatae soluta nesciunt enim iste accusantium sequi officia. Enim beatae omnis a eos adipisci. Consectetur quod ipsum in. Qui rerum est est excepturi.\n\nError minima facere quaerat odio illo. Quibusdam aliquid sint maiores sit alias vitae. Est rem cumque dolores ipsam vel dolorem soluta. Rerum itaque tempore excepturi quis natus. Quia quisquam reprehenderit sit assumenda.\n\nUt quo libero temporibus est dolor debitis aut ut. Reiciendis officiis ut aspernatur provident repellat qui ducimus. Consequuntur blanditiis explicabo aut.', '2002-07-03 03:06:13'),
(41, 'Article #41', 'auteur-41', 'beatae-sequi-voluptatum-in-et-in', 'Qui occaecati eum dolores voluptates molestiae sit. Quia voluptate qui consectetur temporibus. Blanditiis quis et et odio repellendus.\r\n\r\nEt qui ut quasi. Est consequatur nisi rerum inventore. Voluptatem incidunt est incidunt. Veritatis est excepturi eum natus dolorem inventore.\r\n\r\nEx nihil quaerat voluptate numquam earum molestijhjjae et. Doloribus sint qui dolorem incidunt qui quo. Asperiores non tempora molestiae pariatur et magnam culpa esse. Sit ut et consequatur nihil quidem explicabo quos.\r\n\r\nCorrupti voluptatem dolorem quisquam quia et occaecati. Nisi eligendi soluta nobis et. Quibusdam similique magni eius doloremque et. Et eos officiis ut esse assumenda et.\r\n\r\nCumque enim ut neque voluptate necessitatibus. Laborum aut doloremque voluptas repudiandae voluptas voluptas omnis. Unde quia dicta sed in.\r\n\r\nNobis autem labore aliquid illo iste voluptas et. Dolore dolor aspernatur sint deserunt aut expedita voluptas. Explicabo aut magni est molestiae sed eveniet.\r\n\r\nDelectus at et consequatur modi natus. Mollitia eos sunt adipisci culpa aut. Et dolor nostrum soluta optio.\r\n\r\nCupiditate consequatur animi tempora excepturi ut et. Rerum qui voluptatem in assumenda rerum. Consectetur quo iste dignissimos voluptas doloribus eveniet quae.', '2008-11-03 11:16:58'),
(45, 'Article #45', 'auteur-45', 'odio-labore-eos-eteos-etationeatione', 'Ullam illo atque maiores ratione cum totam dignissimos. Ab optio nemo aliquid saepe nobis. Nemo sit illo sed omnis praesentium nam sunt molestiae.\r\n\r\nTempora iste perferendis quia dolor at architecto voluptatem. Distinctio sit rerum omnis rerum et. Earum rerum et maiores. Eum illo distinctio est ipsa id blanditiis in.\r\n\r\nAutem suscipit quod rem est eos id sit a. Architecto unde qui ut atque asperiores repellendus. Possimus deleniti voluptatem et ad aut commodi blanditiis. Laborum voluptates debitis amet neque sequi dolor.\r\n\r\nEt mollitia esse ipsum sapiente placeat consectetur aut esse. Ipsam dolores consequatur quo eos. Accusantium ut totam velit eum. Pariatur architecto est est et debitis. Qui minima qui sapiente vero.', '1993-07-29 17:41:50'),
(48, 'Article #48', 'auteur-48', 'architecto-aut-fuga-vel-illumatione', 'Consequatur laborum temporibus quaerat est. Amet qui sunt asperiores amet eos. Eligendi aperiam maxime similique et ut et.\n\nEst sequi minima similique. Repudiandae adipisci sequi ad possimus autem. Dicta officia est illum asperiores iste placeat ipsam. Aut et sed necessitatibus excepturi ratione sed facilis. Perferendis minus in delectus dolores rem provident.\n\nQuia ut voluptatem ipsa vitae magnam nulla. Et nobis mollitia omnis repudiandae quaerat praesentium. Esse qui adipisci quibusdam omnis ut. Repudiandae vel cupiditate possimus non fugit fuga.\n\nAd inventore aut consequuntur accusamus ullam quam dolorem. Itaque eum vel quia temporibus nihil et. Eligendi sit sapiente delectus odit nisi laudantium nam magni.\n\nError aperiam recusandae et. Ut autem accusantium aperiam quidem. Numquam non accusamus dolores.\n\nEnim aut est ipsa quo. Impedit amet neque labore occaecati inventore repellendus facilis. Ipsum doloremque laboriosam voluptatem consequatur assumenda. Assumenda blanditiis pariatur nulla neque maiores laboriosam voluptas voluptatem.\n\nVero sint iusto nihil deleniti facere autem. Et vero voluptas doloribus tempora non. Officia inventore id sit dolor tempora ratione.\n\nNihil placeat iure odit quam maiores minus. Qui ex nihil qui officiis. Rerum ratione enim molestiae non.\n\nEa doloremque aut voluptatem eum necessitatibus quo. Magni similique dolorem distinctio est ducimus quas mollitia quia. Laboriosam aperiam qui labore et illo exercitationem sunt. Itaque laudantium asperiores voluptatem sit illum ducimus fuga.\n\nRepellat modi laboriosam culpa aut. Sed laborum magni non rerum quam. Voluptas non qui consequuntur harum molestiae deleniti. Voluptatem distinctio sit incidunt est veniam ullam. Eveniet omnis consequuntur id incidunt.\n\nUt corporis vitae nihil maiores iure delectus quia. Quidem reprehenderit nemo quaerat. Aut sed eos architecto quo qui harum. Aut perspiciatis soluta sint.\n\nUllam eum labore neque quia dolorem veniam. Et qui omnis dolorem a et et. Deleniti laboriosam repudiandae nobis molestiae. Ab aperiam illo cupiditate voluptas alias. Similique explicabo minima odio minus ut praesentium.\n\nFugiat quia voluptatem minima a non accusamus. Rerum nihil vel omnis officiis nemo accusantium consequuntur. Sequi ea molestias ea ea repudiandae iusto. Repellat at doloremque adipisci quia non minus voluptas.\n\nVel est sit quam voluptatem. Laudantium voluptas et nostrum ullam voluptates. Harum corrupti dolorum in rerum velit sed.', '1988-01-09 01:28:41'),
(49, 'Article #49', 'auteur-49', 'qui-eveniet-veniam-quasi-quossi-quos', 'Ea et animi iusto deserunt molestias. Distinctio est dolorem nam ex autem aut molestiae.\r\n\r\nExcepturi perferendis error excepturi nihil natus ullam eum ut. Sed et recusandae doloribus. Libero adipisci eligendi eos. Animi velit minus eaque fugit. Quibusdam cum rem ducimus accusamus odio aspernatur.\r\n\r\nNihil possimus ducimus repellat ullam unde corporis. Aut suscipit laborum quas itaque. Tempore nostrum quas tenetur molestiae voluptate molestiae. Id repellat esse nostrum aut in.\r\n\r\nMolestiae ducimus est nemo. Libero libero quae hic aut veniam quis. Quae corporis ab qui. Harum aliquam sit veritatis tempore excepturi odit.\r\n\r\nEt quam exercitationem aperiam et et aut ex. Et illo nihil velit modi numquam placeat dolor. Et molestias sed ea.\r\n\r\nUt quae ut sequi et mollitia. Occaecati temporibus laboriosam aliquid voluptas. Sapiente et quis qui. Atque ea ad deserunt at repudiandae dolorem.\r\n\r\nImpedit ut blanditiis repudiandae sequi incidunt. Atque aspernatur non sint voluptatem.\r\n\r\nEst suscipit cumque sequi culpa. Architecto dolorem voluptatem modi. Minima voluptate est rem debitis tempora itaque suscipit nesciunt. Ut quo corporis tenetur dolor ut.\r\n\r\nDolore pariatur recusandae impedit dolor eum harum. Maiores aut magni consectetur sed. Aut voluptas numquam ea quae quia sed.\r\n\r\nEarum consequuntur suscipit quis voluptatem et. Quasi illo magni exercitationem aliquam quia maiores. Explicabo voluptas minima qui dolor non.\r\n\r\nProvident neque maiores quisquam voluptates praesentium repellendus. Consequatur quo similique non repellendus earum est ut. Fuga error dignissimos cupiditate possimus soluta voluptas fuga nisi. Pariatur saepe consequatur est sint quod et.', '2003-12-16 05:50:36'),
(50, 'Article #50', 'auteur-50', 'autem-ut-at-modi-culpa-et-voluptatum', 'Autem facilis at placeat qui ut natus. A similique voluptatem et dicta nulla dolores qui. Dolores quo aperiam tenetur dolores aperiam alias qui molestias. Quos et inventore temporibus quos.\r\n\r\nNisi tempora harum eveniet autem. Quod quia sed nesciunt provident et ut asperiores velit. Omnis enim quidem pariatur excepturi. Eos enim vitae minima fugit.\r\n\r\nDolore labore non suscipit nostrum libero ut recusandae. Sint consequatur est sequi placeat temporibus. Alias consectetur voluptate voluptas facilis exercitationem atque cum. Aut laboriosam illo id atque ut illum odit voluptas.\r\n\r\nAut nihil eius exercitationem aut repudiandae quia. Fugiat voluptatem repellat ut molestiae quisquam. Sit illum unde ratione beatae est dolorum consectetur esse. Incidunt nostrum doloremque enim eum asperiores eligendi.\r\n\r\nRecusandae autem quia rerum illo impedit. Et atque atque temporibus illo tempora ipsam fugiat. Modi eos debitis qui ut eveniet provident.\r\n\r\nSaepe delectus sint labore doloribus et cupiditate quo. Sit temporibus laboriosam tenetur dolorum maxime qui. Enim atque consequatur perspiciatis. Error accusantium quia quo aut qui. Fugit et ducimus unde voluptate aut consequatur.\r\n\r\nAdipisci vero consectetur laboriosam praesentium. Accusamus nobis perspiciatis ut corrupti vitae. Est sunt ex sint possimus. Maxime sit magni et quos eos qui.', '1985-05-25 11:53:41');

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE
IF NOT EXISTS `user` (
  `id` int
(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` varchar
(255) NOT NULL,
  `email` varchar
(255) NOT NULL,
  `password` varchar
(255) NOT NULL,
  `isAdmin` tinyint
(1) NOT NULL DEFAULT '0',
  PRIMARY KEY
(`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user`
  (`id`, `username
  `, `email`, `password`, `isAdmin`) VALUES
(1, 'admin', 'admin@admin.fr', '$2y$10$xcGf3Upc6qNTi3dUaQczaO8LuNMRzxnKJcHkxWpA8inwEvPlDPYQe', 1),
(2, 'boumediene', 'boumediene@boumediene.com', '$2y$10$ogqPR1cE51Y/M8Nq322b1ehfv9lJar94Xx4w6uqKN0j3ZTwFWfZVK', 0),
(3, 'boum', 'boum@boum.com', '$2y$10$qEHEql/6TAZzf2TdPxluPuVFsUMBLl6nEqqvMogXZuOo0VQ6lsuVS', 0),
(5, 'boumediene', 'boumediene@hotmail.com', '$2y$10$0wqyKy8t.iVuq2JxRB3LkOF4we78i8lfMgDKUFHPVL6k3.oPcFRne', 0);

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `comment`
--
ALTER TABLE `comment`
ADD CONSTRAINT `comment_ibfk_1` FOREIGN KEY
(`postId`) REFERENCES `post`
(`id`) ON
DELETE CASCADE ON
UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
